Convert to Gradle
TsundereBug/discord-intellij pull request #25
Opened 2018-04-24 05:36 UTC by scerruti

Convert build of plugin to Gradle.

2018-04-26 04:54 UTC, s5bug requested changes

2018-04-26 04:54 UTC, TsundereBug commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
This file shouldn't be tracked

2018-04-26 04:54 UTC, TsundereBug commented on .idea/modules.xml
>    <component name="ProjectModuleManager">
Neither should this

2018-04-26 04:54 UTC, TsundereBug commented on .idea/vcs.xml
>  <project version="4">
Or this

2018-04-26 04:54 UTC, TsundereBug commented on discord-intellij.iml
>  <?xml version="1.0" encoding="UTF-8"?>
The IML should not be tracked either

2018-04-26 04:54 UTC, TsundereBug commented on src/main/java/com/tsunderebug/discordintellij/ToggleAction.java
> +import javax.swing.*;
Fix this wildcard

2018-04-27 02:26 UTC, scerruti commented
@TsundereBug requested changes made.

2018-04-27 02:38 UTC, s5bug approved these changes

2018-04-27 02:39 UTC, merged

2018-04-27 02:39 UTC, TsundereBug commented
Keeping open for Vatuu RPC change